[theme]
primaryColor="#58A6FF"
backgroundColor="#000000"
secondaryBackgroundColor="#0D1117"
textColor="#E6EDF3"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
